config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  #メソッド 'コントローラ/アクショaン'

  # For details on the DSL available within thilss file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy, :index]
  
resources :pictures do
  collection do
    post :confirm
    post :contact_mail
  end
  member do  #idメソッドを取得する
    get :contact_mail
  end
end


mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, uniqueness: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }  
  before_validation { email.downcase! }
  mount_uploader :image, ImageUploader
  has_secure_password
  validates :password, presence: true, length: { minimum:6 }, on: :create

  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end

  def index
    @favorite_pictures = current_user.favorite_pictures
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only:[:show, :edit, :update, :destroy]
  def index
    @pictures = Picture.all
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    if params[:back]
      render :new
    else
    if @picture.save
      ContactMailer.contact_mail(@picture).deliver #投稿した時にメイラーのメソッドを呼び出す。
    #redirect_to pictures_path, notice:"投稿を保存しました"
        redirect_to  contact_mail_picture_path(@picture), notice: "投稿を保存しました"
    else
      render :new
    end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
    if @picture.user_id != current_user.id
      redirect_to pictures_path, notice: "他人の投稿なので編集できません"
    end
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "投稿を編集しました"
    else
      render :edit
    end
  end

  def destroy
    if @picture.user_id != current_user.id
      redirect_to pictures_path, notice: "他人の投稿なので削除できません"
    else
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました"
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    @picture.user_id = current_user.id
    render :new if @picture.invalid?
  end

  def contact_mail
    @picture = Picture.find(params[:id])
  end

  private

  def picture_params
    params.require(:picture).permit(:title, :content, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice]  = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id) #URIを作成して、showメソッドに送ります
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id), notice: "他人のプロフィールなので編集できません"
    end
  end

  def update
    # @user = User.new(user_params)
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを編集しました。"
    else
      render :edit
    end
  end

  private


  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h2>お気に入り一覧</h2>

  <% @favorite_pictures.each do |favorite_picture| %>


<table>

<tr>
  <th>タイトル</th>
  <th>内容</th>
</tr>

  <tr>
    <td><%= favorite_picture.title %></td>
    <td><%= favorite_picture.content %></td>
    <td><%= image_tag favorite_picture.image.url %></td>
  </tr>

  </table>
   <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Session</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

     <% if logged_in? %>
     <header>
     <ul>
     <li> <%= link_to "Profile", user_path(current_user.id) %> </li>
     <li> <%= link_to "Logout", session_path(current_user.id), method: :delete %> </li>
      </ul>
      </header>
     <% else %>
     <header>
     <ul>
     <li> <%= link_to "Sign up", new_user_path %> </li>
    <li>  <%= link_to "Login", new_session_path %> </li>
      </ul>
     <% end %>
     </header>

    <%= yield %>

    <footer>ポートフォリオ株式会社</footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class = "picture_contet">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class = "picture_field">
    <%= form.label :image %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

<div class = "actions">
  <%= form.submit %>
 </div>
<% end %>

<%= link_to "投稿一覧画面にもどる", pictures_path %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>

  <p>タイトル:<%= @picture.title %></p>
  <p>本文:<%= @picture.content %></p>
  <p>画像:<%= image_tag @picture.image.url %>
  <%= form.submit  "登録する" %>

  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/contact_mail.html.erb
<h1>投稿が完了しました</h1>

<h4>投稿内容の確認</h4>

<h4>title: <%= @picture.title %></h4>
<p>content: <%= @picture.content %></p>

app/views/pictures/edit.html.erb
<h2>投稿内容を編集する</h2>
<%= render 'form' %>

<!--<%= form_with(model: @picture, local: true) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class = "picture_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class = "picture_contet">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class = "picture_field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>


  <%= form.submit %>
<% end %> -->

app/views/pictures/index.html.erb
<% if logged_in? %>

<h1>投稿一覧</h1>

<p><%= notice %></p>
<table>
  <tr>
    <th>投稿者</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>画像</th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%= picture.user.name %></td>
    <td><%= picture.title %></td>
    <td><%= picture.content %></td>
    <td><%= image_tag picture.image.url %></td>

    <td><%= link_to '詳細を確認する', picture_path(picture.id) %></td>
    <% if current_user.id == picture.user_id %>
    <td><%= link_to "ブログを編集する", edit_picture_path(picture.id), data: { confirm: '本当に編集していいですか？' } %><td>
    <td><%= link_to 'ブログを削除する', picture_path(picture.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    <% end %>
  </tr>

<% end %>
</table>

<br>

<%= link_to '新規投稿する', new_picture_path %>

<% end %>

app/views/pictures/new.html.erb
<% if logged_in? %>
<h2>新規投稿する</h2>
<%= render 'form' %>
<% end %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<p>タイトル: <%= @picture.title %></p>
<p>内容: <%= @picture.content %></p>
<p>画像: <%=image_tag @picture.image.url %></p>

<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

<%= link_to "投稿一覧画面にもどる", pictures_path %>
<%= link_to "新規投稿画面に移る", new_picture_path %>

app/views/users/edit.html.erb
<h2>プロフィール内容を編集する</h2>

<%= form_with(model: @user,local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
        </ul>
        </div>
        <% end %>

    <div class = "user_name">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class = "user_email">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class = "user_image">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>



    <%= form.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation"><!--railsがデフォルトで用意しているエラー用スタイル-->
    <h2><%= pluralize(@user.errors.count, "") %> 件のエラーがあります</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス:<%= @user.email %></p>

<p>プロフィール画像:<%= image_tag(@user.image.url) if @user.image.url.present? %></p>

<%= link_to "投稿一覧画面にもどる", pictures_path %>
<br>
<%= link_to "新規投稿画面に移る", new_picture_path %>
<br>
<%= link_to "プロフィールを編集する", edit_user_path(@user.id) %>
<br>
<%= link_to "お気に入りを表示する", favorites_path %>